# Generated by Django 4.0.4 on 2022-05-14 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aquene_app', '0005_alter_add_firm_id_alter_don_reg_id_alter_feedback_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trust_don',
            name='select_trust',
        ),
        migrations.AddField(
            model_name='trust_don',
            name='trust_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aquene_app.trust_reg'),
        ),
    ]
