# Generated by Django 4.0.4 on 2022-05-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquene_app', '0006_remove_trust_don_select_trust_trust_don_trust_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='don_reg',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='officer_reg',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orph_reg',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trust_reg',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='don_reg',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='officer_reg',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
