# Generated by Django 4.0.4 on 2022-05-14 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aquene_app', '0007_don_reg_name_officer_reg_name_orph_reg_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orph_don',
            name='orph_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aquene_app.orph_reg'),
        ),
    ]
