# Generated by Django 4.1.1 on 2022-10-25 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aquene_app', '0009_rename_orph_id_orph_don_orph'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='trust_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aquene_app.trust_reg'),
        ),
    ]
