# Generated by Django 4.1.1 on 2022-10-25 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquene_app', '0010_sponsor_trust_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='trust_id',
            new_name='trust',
        ),
    ]
