# Generated by Django 4.1.1 on 2022-10-25 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquene_app', '0011_rename_trust_id_sponsor_trust'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_firm',
            old_name='orp_id',
            new_name='orp',
        ),
        migrations.RenameField(
            model_name='add_firm',
            old_name='trust_id',
            new_name='trust',
        ),
    ]
