# Generated by Django 4.0.5 on 2022-11-03 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aquene_app', '0012_rename_orp_id_add_firm_orp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='trust',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='firm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aquene_app.add_firm'),
        ),
    ]
