# Generated by Django 4.1.7 on 2023-04-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquene_app', '0014_orph_don_date_orph_don_others_trust_don_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orph_reg',
            name='district',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orph_reg',
            name='image',
            field=models.ImageField(max_length=20, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='orph_reg',
            name='place',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trust_reg',
            name='district',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trust_reg',
            name='image',
            field=models.ImageField(max_length=20, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='trust_reg',
            name='place',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orph_reg',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
