# Generated by Django 4.1.7 on 2023-04-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquene_app', '0015_orph_reg_district_orph_reg_image_orph_reg_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trust_reg',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
