# Generated by Django 4.1.7 on 2023-04-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquene_app', '0016_alter_trust_reg_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='don_reg',
            name='district',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='don_reg',
            name='image',
            field=models.ImageField(max_length=20, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='don_reg',
            name='place',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='officer_reg',
            name='district',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='officer_reg',
            name='image',
            field=models.ImageField(max_length=20, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='officer_reg',
            name='place',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
