# Generated by Django 4.1.7 on 2023-04-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquene_app', '0017_don_reg_district_don_reg_image_don_reg_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='don_reg',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='officer_reg',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='orph_reg',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='trust_reg',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
