# Generated by Django 4.1.7 on 2023-04-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquene_app', '0018_alter_don_reg_image_alter_officer_reg_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_firm',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='add_firm',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
