# Generated by Django 4.1.7 on 2023-04-25 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aquene_app', '0019_add_firm_description_add_firm_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aquene_app.don_reg'),
        ),
    ]
