# Generated by Django 4.1.7 on 2023-04-25 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquene_app', '0020_alter_sponsor_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orph_don',
            old_name='dress',
            new_name='study',
        ),
        migrations.RemoveField(
            model_name='orph_don',
            name='food',
        ),
        migrations.RemoveField(
            model_name='orph_don',
            name='medical',
        ),
    ]
