# Generated by Django 4.1.7 on 2023-04-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquene_app', '0021_rename_dress_orph_don_study_remove_orph_don_food_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='don_reg',
            name='proof',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='officer_reg',
            name='proof',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='orph_reg',
            name='proof',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='trust_reg',
            name='proof',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
